[2022-02-17 06:23:13,034] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: FfailMailTestEachTask_dag.task5 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:23:13,039] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: FfailMailTestEachTask_dag.task5 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:23:13,039] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:23:13,039] {__init__.py:1354} INFO - Starting attempt 1 of 1
[2022-02-17 06:23:13,039] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:23:13,049] {__init__.py:1374} INFO - Executing <Task(BashOperator): task5> on 2022-02-16T00:00:00+00:00
[2022-02-17 06:23:13,049] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'FfailMailTestEachTask_dag', 'task5', '2022-02-16T00:00:00+00:00', '--job_id', '141', '--raw', '-sd', 'DAGS_FOLDER/FFFailMailTestEachTask.py', '--cfg_path', '/tmp/tmpnefe4h29']
[2022-02-17 06:23:13,432] {base_task_runner.py:101} INFO - Job 141: Subtask task5 [2022-02-17 06:23:13,432] {__init__.py:51} INFO - Using executor SequentialExecutor
[2022-02-17 06:23:13,587] {base_task_runner.py:101} INFO - Job 141: Subtask task5 [2022-02-17 06:23:13,587] {__init__.py:305} INFO - Filling up the DagBag from /home/jovyan/airflow/dags/FFFailMailTestEachTask.py
[2022-02-17 06:23:13,598] {base_task_runner.py:101} INFO - Job 141: Subtask task5 [2022-02-17 06:23:13,597] {cli.py:517} INFO - Running <TaskInstance: FfailMailTestEachTask_dag.task5 2022-02-16T00:00:00+00:00 [running]> on host 4c5aeb1c47d1
[2022-02-17 06:23:13,607] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2022-02-17 06:23:13,607] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=FfailMailTestEachTask_dag
AIRFLOW_CTX_TASK_ID=task5
AIRFLOW_CTX_EXECUTION_DATE=2022-02-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-16T00:00:00+00:00
[2022-02-17 06:23:13,607] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmp696qx923/task5euxy4kqk
[2022-02-17 06:23:13,607] {bash_operator.py:114} INFO - Running command: exit(1)
[2022-02-17 06:23:13,611] {bash_operator.py:123} INFO - Output:
[2022-02-17 06:23:13,611] {bash_operator.py:127} INFO - /tmp/airflowtmp696qx923/task5euxy4kqk: line 1: syntax error near unexpected token `1'
[2022-02-17 06:23:13,611] {bash_operator.py:127} INFO - /tmp/airflowtmp696qx923/task5euxy4kqk: line 1: `exit(1)'
[2022-02-17 06:23:13,611] {bash_operator.py:131} INFO - Command exited with return code 2
[2022-02-17 06:23:13,615] {__init__.py:1580} ERROR - Bash command failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:23:13,616] {__init__.py:1611} INFO - Marking task as FAILED.
[2022-02-17 06:23:13,806] {logging_mixin.py:95} INFO - [2022-02-17 06:23:13,806] {email.py:126} INFO - Sent an alert email to ['sondonghyun7@hyundai.com']
[2022-02-17 06:23:13,977] {base_task_runner.py:101} INFO - Job 141: Subtask task5 Traceback (most recent call last):
[2022-02-17 06:23:13,977] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/bin/airflow", line 32, in <module>
[2022-02-17 06:23:13,977] {base_task_runner.py:101} INFO - Job 141: Subtask task5     args.func(args)
[2022-02-17 06:23:13,977] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     return f(*args, **kwargs)
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     _run(args, dag, ti)
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     pool=args.pool,
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     return func(*args, **kwargs)
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     result = task_copy.execute(context=context)
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5   File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5     raise AirflowException("Bash command failed")
[2022-02-17 06:23:13,978] {base_task_runner.py:101} INFO - Job 141: Subtask task5 airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:23:18,040] {logging_mixin.py:95} INFO - [2022-02-17 06:23:18,040] {jobs.py:2562} INFO - Task exited with return code 1
