[2022-02-17 06:06:05,426] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:06:05,431] {__init__.py:1139} INFO - Dependencies all met for <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [queued]>
[2022-02-17 06:06:05,431] {__init__.py:1353} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:06:05,431] {__init__.py:1354} INFO - Starting attempt 4 of 4
[2022-02-17 06:06:05,431] {__init__.py:1355} INFO - 
--------------------------------------------------------------------------------
[2022-02-17 06:06:05,440] {__init__.py:1374} INFO - Executing <Task(BashOperator): test> on 2022-02-16T00:00:00+00:00
[2022-02-17 06:06:05,440] {base_task_runner.py:119} INFO - Running: ['airflow', 'run', 'failMailTestEachTask_dag', 'test', '2022-02-16T00:00:00+00:00', '--job_id', '127', '--raw', '-sd', 'DAGS_FOLDER/failMailTestEachTask.py', '--cfg_path', '/tmp/tmp8by2pq35']
[2022-02-17 06:06:05,838] {base_task_runner.py:101} INFO - Job 127: Subtask test [2022-02-17 06:06:05,837] {__init__.py:51} INFO - Using executor SequentialExecutor
[2022-02-17 06:06:05,998] {base_task_runner.py:101} INFO - Job 127: Subtask test [2022-02-17 06:06:05,997] {__init__.py:305} INFO - Filling up the DagBag from /home/jovyan/airflow/dags/failMailTestEachTask.py
[2022-02-17 06:06:06,008] {base_task_runner.py:101} INFO - Job 127: Subtask test [2022-02-17 06:06:06,008] {cli.py:517} INFO - Running <TaskInstance: failMailTestEachTask_dag.test 2022-02-16T00:00:00+00:00 [running]> on host 4c5aeb1c47d1
[2022-02-17 06:06:06,022] {bash_operator.py:81} INFO - Tmp dir root location: 
 /tmp
[2022-02-17 06:06:06,023] {bash_operator.py:90} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=failMailTestEachTask_dag
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-02-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-16T00:00:00+00:00
[2022-02-17 06:06:06,023] {bash_operator.py:104} INFO - Temporary script location: /tmp/airflowtmpdwaus1cq/test6csrr0n1
[2022-02-17 06:06:06,023] {bash_operator.py:114} INFO - Running command: exit(1)
[2022-02-17 06:06:06,027] {bash_operator.py:123} INFO - Output:
[2022-02-17 06:06:06,027] {bash_operator.py:127} INFO - /tmp/airflowtmpdwaus1cq/test6csrr0n1: line 1: syntax error near unexpected token `1'
[2022-02-17 06:06:06,027] {bash_operator.py:127} INFO - /tmp/airflowtmpdwaus1cq/test6csrr0n1: line 1: `exit(1)'
[2022-02-17 06:06:06,027] {bash_operator.py:131} INFO - Command exited with return code 2
[2022-02-17 06:06:06,031] {__init__.py:1580} ERROR - Bash command failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:06:06,033] {__init__.py:1611} INFO - Marking task as FAILED.
[2022-02-17 06:06:06,221] {logging_mixin.py:95} INFO - [2022-02-17 06:06:06,221] {email.py:126} INFO - Sent an alert email to ['sondonghyun7@hyundai.com']
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test Traceback (most recent call last):
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/bin/airflow", line 32, in <module>
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     args.func(args)
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     return f(*args, **kwargs)
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 523, in run
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     _run(args, dag, ti)
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/bin/cli.py", line 442, in _run
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     pool=args.pool,
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     return func(*args, **kwargs)
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/models/__init__.py", line 1441, in _run_raw_task
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     result = task_copy.execute(context=context)
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test   File "/opt/conda/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 135, in execute
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test     raise AirflowException("Bash command failed")
[2022-02-17 06:06:06,397] {base_task_runner.py:101} INFO - Job 127: Subtask test airflow.exceptions.AirflowException: Bash command failed
[2022-02-17 06:06:10,426] {logging_mixin.py:95} INFO - [2022-02-17 06:06:10,426] {jobs.py:2562} INFO - Task exited with return code 1
